server:
  error:
    whitelabel:
      enabled: false
spring:
  datasource:
    password: ''
    url: 'jdbc:h2:mem:usersdb  '
    username: root
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
